version: "3.9"

services:
  ocr-tester:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    # GPU chahiye toh uncomment karo + nvidia-container-toolkit install karo
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
